# Generated by Django 2.2.6 on 2019-10-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.FloatField(default=1.0)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=16)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='rates.Currency')),
            ],
        ),
    ]
