# Generated by Django 2.2.6 on 2019-10-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='volume',
            field=models.DecimalField(decimal_places=8, max_digits=24),
        ),
    ]
